### ISSUE TITLE
Can not run foundation-cli

### ISSUE THREAD

**Issue by okc0mputer** [foundation/foundation-cli#119]
➜  foundationtemplate foundation -v
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/usr/local/lib/node_modules/foundation-cli/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/usr/local/lib/node_modules/foundation-cli/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/foundation-cli/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)

**Comment by joaodfmota** [comment]
It seems that `foundation-cli` doesn't work with your node version

If you are using node 12 follow these steps:

Clone this repo:
```git clone https://github.com/zurb/foundation-emails-template project```

Edit `package.json`
`"gulp": "git+https://github.com/gulpjs/gulp.git#4.0",` to `"gulp": "^4.0.0",`
`"gulp-sass": "^2.1.0",` to `"gulp-sass": "^4.0.0",`

Run: `npm i`

**Comment by okc0mputer** [comment]
I'm actually using node 13.1 on macos catalina.  I checked the package.json file and it does contain gulp 4.0.0 and gulp-sass 4.0.1, any other suggestions?

**Comment by joaodfmota** [comment]
> I'm actually using node 13.1 on macos catalina. I checked the package.json file and it does contain gulp 4.0.0 and gulp-sass 4.0.1, any other suggestions?

Sorry, I've forgotten to mention that I'm using only the emails.

You can use nvm and install node 10 to use the cli.

Or

Just clone the repo that you wanna use:
```https://github.com/foundation/foundation-sites```
```https://github.com/foundation/foundation-emails```

**Comment by okc0mputer** [comment]
I'm not into node so i'll stick with cloning the repo.  I think a few lines of ruby or python could replace the existing foundation-cli with much better compatibility.  Thanks for the advice
