### ISSUE TITLE
Foundation CLI not working – primordials not defined.

### ISSUE THREAD

**Issue by billyromano** [foundation/foundation-cli#121]
Trying to setup a new Foundation for Emails project and I'm getting this error:
fs.js:35
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (/Users/user/.npm-packages/lib/node_modules/foundation-cli/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/user/.npm-packages/lib/node_modules/foundation-cli/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/user/.npm-packages/lib/node_modules/foundation-cli/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)

**Comment by billyromano** [comment]
Installed using npm. Tested using node v12 and 13.

**Comment by billyromano** [comment]
node v12 shows this error output:
fs.js:27
const { Math, Object } = primordials;

**Comment by billyromano** [comment]
Installing node v10 works as a temporary solution. This package should be updated to support newer node versions.

**Comment by DanielRuf** [comment]
Hi, please see https://github.com/foundation/foundation-cli/issues?q=is%3Aissue+primordials+is%3Aclosed

We are aware of that. You can easily switch to Node 10 using `nvm`, `nodenv` or `n`.
