### ISSUE TITLE
Error in nodejs version 12.16.1

### ISSUE THREAD

**Issue by felkeM** [foundation/foundation-cli#124]
fs.js:35
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (/usr/lib/node_modules/foundation-cli/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/usr/lib/node_modules/foundation-cli/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/usr/lib/node_modules/foundation-cli/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)

**Comment by DanielRuf** [comment]
Hi, @felkeM 

please use the search. This is a known issue with node >= 10 and the gulp version.

Please switch to node 10 or 8 using nodenv.

This will be fixed with upcoming releases.

**Comment by DanielRuf** [comment]
See https://github.com/foundation/foundation-cli/search?q=primordials&type=Issues

**Comment by SamuelTrimble** [comment]
Why are all issues related to this marked as "closed"? There is a workaround sure, but it's obviously still an open issue as everyone trying to use the cli with a modern version of node will hit this. Is there an open issue related to this that I'm not seeing? If so, it might be more helpful to point people to that instead of a search that just shows closed issues.

**Comment by DanielRuf** [comment]
It is on our roadmap to fix this. But not right now.

> This will be fixed with upcoming releases.

**Comment by gregorydk** [comment]
> It is on our roadmap to fix this. But not right now.
> 
> > This will be fixed with upcoming releases.

Not right now? Shouldn't this be a priority? Version 14 is the current stable version. Node.js 12 is the current LTS and version 10 is in maintenance mode and will be EOL this October!

**Comment by DanielRuf** [comment]
> Not right now? Shouldn't this be a priority? Version 14 is the current stable version. Node.js 12 is the current LTS and version 10 is in maintenance mode and will be EOL this October!

The only thing that the CLI is does is the following:
* clone [foundation-zurb-template](https://github.com/foundation/foundation-zurb-template) using `git`
* run `npm i`

See https://github.com/foundation/foundation-cli/blob/9afb15ca1c081f009d880b9ed35bf0c97d20b57e/lib/commands/new.js#L28
