### ISSUE TITLE
internalBinding is not defined

### ISSUE THREAD

**Issue by morsecodemedia** [foundation/foundation-cli#132]
**Version:**  foundation-cli@2.2.5
**OS:** macOS Sierra 10.12.6
**Node:** 10.16.3
**NPM:** 6.14.6

**Error:**
```
internal/util/inspect.js:31
const types = internalBinding('types');
              ^

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/usr/local/lib/node_modules/foundation-cli/node_modules/natives/index.js:137:5)
    at require (/usr/local/lib/node_modules/foundation-cli/node_modules/natives/index.js:110:12)
    at util.js:25:21
    at req_ (/usr/local/lib/node_modules/foundation-cli/node_modules/natives/index.js:137:5)
    at require (/usr/local/lib/node_modules/foundation-cli/node_modules/natives/index.js:110:12)
    at fs.js:42:21
    at req_ (/usr/local/lib/node_modules/foundation-cli/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/usr/local/lib/node_modules/foundation-cli/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/foundation-cli/node_modules/graceful-fs/fs.js:1:37)
```

**How to reproduce:**
run any `foundation` command
_Examples:_
`foundation -v`
`foundation new`
`foundation new --framework emails`

**Comment by DanielRuf** [comment]
This is an issue with the graceful-fs dependency natives. Please see https://www.google.com/search?client=ubuntu&channel=fs&q=ReferenceError%3A+internalBinding+is+not+defined+nodejs&ie=utf-8&oe=utf-8

Probably in combination with the Nodejs version.

**Comment by DanielRuf** [comment]
See https://stackoverflow.com/a/55412641/753676 and other relevant solutions. Updating `natives` should resolve this. Closing as this is a third-party dependency issue.

**Comment by DanielRuf** [comment]
Also check if Node 12 works.

**Comment by DanielRuf** [comment]
Also check if Node 8 works.

**Comment by DanielRuf** [comment]
Can not reproduce with a clean install and using it locally (on Ubuntu):

![image](https://user-images.githubusercontent.com/827205/88806719-129e4400-d1b1-11ea-9249-f76fc39a9d5c.png)
