### ISSUE TITLE
foundation-cli, error after error...

### ISSUE THREAD

**Issue by yeltsinxyz** [foundation/foundation-cli#139]
Hello,

First let me show the versions I already tried:

```
14.16.0
12.16.3
* 10.23.3 (Currently using 64-bit executable)
0.10.48
0.10.19
```

The current error is:

```
Error: missing script: build
    at run (C:\Users\yelts\AppData\Roaming\nvm\v10.23.3\node_modules\foundation-cli\node_modules\npm\lib\run-script.js:142:19)
    at C:\Users\yelts\AppData\Roaming\nvm\v10.23.3\node_modules\foundation-cli\node_modules\npm\lib\run-script.js:58:5
    at C:\Users\yelts\AppData\Roaming\nvm\v10.23.3\node_modules\foundation-cli\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
    at checkBinReferences_ (C:\Users\yelts\AppData\Roaming\nvm\v10.23.3\node_modules\foundation-cli\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
    at final (C:\Users\yelts\AppData\Roaming\nvm\v10.23.3\node_modules\foundation-cli\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
    at then (C:\Users\yelts\AppData\Roaming\nvm\v10.23.3\node_modules\foundation-cli\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
    at C:\Users\yelts\AppData\Roaming\nvm\v10.23.3\node_modules\foundation-cli\node_modules\npm\node_modules\read-package-json\read-json.js:243:12
    at C:\Users\yelts\AppData\Roaming\nvm\v10.23.3\node_modules\foundation-cli\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

But I already got at least three different errors:

### First

```
PS D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page> foundation build

> underscores@1.0.0 build D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page
> node-sass


D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\node_modules\node-sass\lib\binding.js:15
      throw new Error(errors.missingBinary());
            ^
Error: Missing binding D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\node_modules\node-sass\vendor\win32-x64-11\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node 0.10.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 14.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\node_modules\node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\node_modules\node-sass\bin\node-sass:10:10)
    at Module._compile (module.js:456:26)
Error: underscores@1.0.0 build: `node-sass`
Exit status 8
    at EventEmitter.<anonymous> (C:\Users\yelts\AppData\Roaming\nvm\v0.10.48\node_modules\foundation-cli\node_modules\npm\lib\utils\lifecycle.js:217:16)
    at EventEmitter.emit (events.js:98:17)
    at ChildProcess.<anonymous> (C:\Users\yelts\AppData\Roaming\nvm\v0.10.48\node_modules\foundation-cli\node_modules\npm\lib\utils\spawn.js:24:14)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
```

### Second

People said: Run this before `npm rebuild node-sass`

```
> node-sass@4.14.1 install D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\node_modules\node-sass
> node scripts/install.js


D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\node_modules\wide-align\node_modules\string-width\index.js:2
const stripAnsi = require('strip-ansi');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\node_modules\wide-align\align.js:2:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

npm ERR! Windows_NT 10.0.19042
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "node-sass"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! node-sass@4.14.1 install: `node scripts/install.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the node-sass@4.14.1 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\npm-debug.log
```

### Third

People said there was a bug in foundation-cli where the `foundation build` was not using gulp sass. So I decided to put on package.json.

```
PS D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page> foundation build

> underscores@1.0.0 build D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page
> gulp sass

'gulp' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.
Error: underscores@1.0.0 build: `gulp sass`
Exit status 1
    at EventEmitter.<anonymous> (C:\Users\yelts\AppData\Roaming\nvm\v0.10.48\node_modules\foundation-cli\node_modules\npm\lib\utils\lifecycle.js:217:16)
    at EventEmitter.emit (events.js:98:17)
    at ChildProcess.<anonymous> (C:\Users\yelts\AppData\Roaming\nvm\v0.10.48\node_modules\foundation-cli\node_modules\npm\lib\utils\spawn.js:24:14)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
```

### Fourth 

```
PS D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page> npm install -g gulp-cli
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
C:\Program Files\nodejs\gulp -> C:\Program Files\nodejs\node_modules\gulp-cli\bin\gulp.js
+ gulp-cli@2.3.0
added 246 packages from 165 contributors in 24.226s
PS D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page> foundation build
Error: missing script: build
    at run (C:\Users\yelts\AppData\Roaming\nvm\v10.23.3\node_modules\foundation-cli\node_modules\npm\lib\run-script.js:142:19)
    at C:\Users\yelts\AppData\Roaming\nvm\v10.23.3\node_modules\foundation-cli\node_modules\npm\lib\run-script.js:58:5
    at C:\Users\yelts\AppData\Roaming\nvm\v10.23.3\node_modules\foundation-cli\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
    at checkBinReferences_ (C:\Users\yelts\AppData\Roaming\nvm\v10.23.3\node_modules\foundation-cli\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
    at final (C:\Users\yelts\AppData\Roaming\nvm\v10.23.3\node_modules\foundation-cli\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
    at then (C:\Users\yelts\AppData\Roaming\nvm\v10.23.3\node_modules\foundation-cli\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
    at C:\Users\yelts\AppData\Roaming\nvm\v10.23.3\node_modules\foundation-cli\node_modules\npm\node_modules\read-package-json\read-json.js:243:12
    at C:\Users\yelts\AppData\Roaming\nvm\v10.23.3\node_modules\foundation-cli\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

### Last

```
PS D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page> foundation new
? What are you building today? A website (Foundation for Sites)
? What's the project called? (no spaces) foundation
? Which template would you like to use? Basic Template: includes a Sass compiler

            .
           /|     ,
      , /|/  \/| /|       Thanks for using ZURB Foundation for Sites!
     /|/       |/ |       -------------------------------------------
 |___|            |___|   Let's set up a new project.
 \___|  ^^   ^^   |___/   It shouldn't take more than a minute.
     | -[O]--[O]- |
     |    ___,    |
     |    ...     |
      \__________/


Downloading the project template...
Done downloading!

Installing dependencies...


> bufferutil@4.0.3 install D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\foundation\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\bufferutil
> node-gyp-build

\
> utf-8-validate@5.0.4 install D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\foundation\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\utf-8-validate
> node-gyp-build


> utf-8-validate@5.0.4 install D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\foundation\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\utf-8-validate
> node-gyp-build


> bufferutil@4.0.3 install D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\foundation\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\bufferutil
> node-gyp-build


> bufferutil@4.0.3 install D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\foundation\node_modules\browser-sync\node_modules\browser-sync-ui\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\bufferutil
> node-gyp-build


> utf-8-validate@5.0.4 install D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\foundation\node_modules\browser-sync\node_modules\browser-sync-ui\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\utf-8-validate
> node-gyp-build

|[0G/
> node-sass@4.14.1 install D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\foundation\node_modules\gulp-sass\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\yelts\AppData\Roaming\npm-cache\node-sass\4.14.1\win32-x64-64_binding.node

> node-sass@4.14.1 postinstall D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\foundation\node_modules\gulp-sass\node_modules\node-sass
> node scripts/build.js

Binary found at D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\foundation\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-x64-64\binding.node
Testing binary
Binary has a problem: { Error: Cannot find module './stubFalse'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\foundation\node_modules\gulp-sass\node_modules\lodash\isBuffer.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }
Building the binary locally
Building: C:\Program Files\nodejs\node.exe D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\foundation\node_modules\gulp-sass\node_modules\node-sass\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'D:\\Sites\\lendico-landing-page\\app\\public\\wp-content\\themes\\lendico-landing-page\\foundation\\node_modules\\gulp-sass\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.23.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\foundation\node_modules\gulp-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\foundation\node_modules\gulp-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\foundation\node_modules\gulp-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\foundation\node_modules\gulp-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\foundation\node_modules\gulp-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\foundation\node_modules\gulp-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\foundation\node_modules\gulp-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\foundation\node_modules\gulp-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\foundation\node_modules\gulp-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\foundation\node_modules\gulp-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\foundation\node_modules\gulp-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\foundation\node_modules\gulp-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (D:\\Sites\\lendico-landing-page\\app\\public\\wp-content\\themes\\lendico-landing-page\\foundation\\node_modules\\gulp-sass\\node_modules\\node-sass\\node_modules\\node-gyp\\node_modules\\which\\which.js:13:12)\n    at F (D:\\Sites\\lendico-landing-page\\app\\public\\wp-content\\themes\\lendico-landing-page\\foundation\\node_modules\\gulp-sass\\node_modules\\node-sass\\node_modules\\node-gyp\\node_modules\\which\\which.js:68:19)\n    at E (D:\\Sites\\lendico-landing-page\\app\\public\\wp-content\\themes\\lendico-landing-page\\foundation\\node_modules\\gulp-sass\\node_modules\\node-sass\\node_modules\\node-gyp\\node_modules\\which\\which.js:80:29)\n    at D:\\Sites\\lendico-landing-page\\app\\public\\wp-content\\themes\\lendico-landing-page\\foundation\\node_modules\\gulp-sass\\node_modules\\node-sass\\node_modules\\node-gyp\\node_modules\\which\\which.js:89:16\n    at D:\\Sites\\lendico-landing-page\\app\\public\\wp-content\\themes\\lendico-landing-page\\foundation\\node_modules\\gulp-sass\\node_modules\\node-sass\\node_modules\\node-gyp\\node_modules\\which\\node_modules\\isexe\\index.js:42:5\n    at D:\\Sites\\lendico-landing-page\\app\\public\\wp-content\\themes\\lendico-landing-page\\foundation\\node_modules\\gulp-sass\\node_modules\\node-sass\\node_modules\\node-gyp\\node_modules\\which\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:153:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\yelts\AppData\Local\Programs\Python\Python39\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\yelts\AppData\Local\Programs\Python\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Sites\\lendico-landing-page\\app\\public\\wp-content\\themes\\lendico-landing-page\\foundation\\node_modules\\gulp-sass\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\Sites\lendico-landing-page\app\public\wp-content\themes\lendico-landing-page\foundation\node_modules\gulp-sass\node_modules\node-sass
gyp ERR! node -v v10.23.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
-
There were some problems during the installation.

 ✓ New project folder created.
 ✗ Node modules not installed. Try running npm install manually.
 ✓ Bower components installed.

Once you've resolved the above issues, run foundation watch while inside the foundation folder.
```

---

Since people asks:

```
PS D:\Sites\lendico-landing-page\app\public\wp-content\themes> node --version
v10.23.3
PS D:\Sites\lendico-landing-page\app\public\wp-content\themes> npm --version
6.14.11
```

I spent 8 hours today, trying to fix it. And 4 more hours yesterday.

**Comment by yeltsinxyz** [comment]
For people with the same issue: 

**Install nvm and use Node version 10.23.3.**
