### ISSUE TITLE
Issues after updating to foundation-cli 2.3.0

### ISSUE THREAD

**Issue by mihail-minkov** [foundation/foundation-cli#146]
So, I was planning to do some work today early in the morning.

Used to have 2.2.6 installed, running on node 10.20.1 using nvm. I tried updating using that node version and when running any foundation command I started getting this error:

```
SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Object.<anonymous> (C:\nvm\v10.20.1\node_modules\foundation-cli\node_modules\string-kit\li    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

I checked the update log and saw these lines:

```
npm WARN notsup Unsupported engine for foundation-cli@2.3.0: wanted: {"node":">=12.0"} (current: {"node":"10.20.1","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: foundation-cli@2.3.0
npm WARN notsup Unsupported engine for terminal-kit@2.2.2: wanted: {"node":">=14.15.0"} (current: {"node":"10.20.1","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: terminal-kit@2.2.2
npm WARN notsup Unsupported engine for string-kit@0.14.3: wanted: {"node":">=14.15.0"} (current: {"node":"10.20.1","npm":"6.14.4"})
```

So, since Foundation didn't use to run on newer versions of node I supposed the update fixed this, so I added 16.13.0 LTS to my nvm and used that version instead.

Then I ran `npm install -g foundation-cli`. Installation ran smoothly and after that when running `foundation -v` I get a firm response that says:

```
Foundation CLI version 2.3.0
```

I then run `foundation new` select website and instead of taking a while as it used to, it goes almost instantly and shows this:

```
Downloading the project template...
Done downloading!

Installing dependencies...

undefined

There were some problems during the installation.

 ✓ New project folder created.

Once you've resolved the above issues, run foundation watch while inside the testfoundation folder.
```

If I go to the testfoundation folder and run `yarn install` the process runs smooth and shows no errors.

```
yarn install v1.22.15
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 60.06s.
```

Then I try to run `foundation watch` and I get this error:

```
PS C:\projects\testfoundation> foundation watch
C:\nvm\v16.13.0\node_modules\foundation-cli\lib\commands\watch.js:26
    npm.commands.start.apply(this, []);
                       ^

TypeError: npm.commands.start.apply is not a function
    at C:\nvm\v16.13.0\node_modules\foundation-cli\lib\commands\watch.js:26:24
```
I am on Windows 10 21H1 build 19043.1348 using nvm for node and npm.

I also tried using node 14.18.1, same error message.

**Comment by favcodr71** [comment]
Try an older version `npm install -g foundatin-cli@2.2.6` with node v11.

**Comment by mihail-minkov** [comment]
I actually read the update notes later on and using `yarn start` did the trick for me. I just had to delete my node_modules folder and run `yarn install` because of the new node version.

Hope the Foundation guys can fix those small issues. Otherwise pretty great that foundation-cli now works with newer versions of node 👍
