### ISSUE TITLE
Foundation watch error

### ISSUE THREAD

**Issue by copaou** [foundation/foundation-cli#148]
Hi!
I am experiencing an error when I am trying to execute the 'foundation watch' command or even the "foundation-v"

The response is:

`C:\Users\Costas\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\string-kit\lib\format.js:327
                markupTarget = this.shiftedMarkup?.[ runtime.shift ]?.[ markup ] ;
                                                  ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\Costas\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\string-kit\lib\string.js:62:2)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)`

Packages versions:
Node: v12.22.8
npm: 6.14.15

Any help?
Thanks in advance

**Comment by copaou** [comment]
Update: I have the same problem when I try to run 'foundation new',

**Comment by joeworkman** [comment]
Try node 14
